; Include ASM files to main

%INCLUDE "drawAll.asm"
%INCLUDE "app.asm"
%INCLUDE "getStringG.asm"
%INCLUDE "WriteInt.asm"
%INCLUDE "calculator.asm"
%INCLUDE "graphicsmode.asm"
%INCLUDE "time.asm"
%INCLUDE "repeat.asm"
%INCLUDE "reset.asm"
%INCLUDE "help.asm"
%INCLUDE "clear.asm"
%INCLUDE "about.asm"
%INCLUDE "printString.asm"
%INCLUDE "getPassword.asm"
%INCLUDE "getString.asm"
%INCLUDE "strcmp.asm"
%INCLUDE "strcp.asm"
%INCLUDE "login.asm"
%INCLUDE "setlogin.asm"
